# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

	config.vm.box = "dev"
	config.vm.box = ENV['HOME']+"/Projects/resources/packaged-vagrant-boxes/centos-7-1503-01-minimal.box"

	config.vm.define "docker" do |docker|

	#	docker.vm.network "private_network", ip: "192.168.33.11"
		docker.vm.provision "shell", inline: "sudo sysctl kernel.hostname=docker.example.com"
		docker.vm.provision "shell", inline: "sudo systemctl stop firewalld"

		# Instructions: https://docs.docker.com/installation/centos/
		docker.vm.provision "shell", inline:  "sudo yum -y localinstall --nogpgcheck /vagrant/docker-engine-1.7.1-1.el7.centos.x86_64.rpm"
		docker.vm.provision "shell", inline:  "sudo service docker start"
		docker.vm.provision "shell", inline:  "systemctl enable docker.service"
		docker.vm.provision "shell", inline:  "sudo usermod -aG docker vagrant"


	end

end
